### ISSUE TITLE
4.00 sources 

### ISSUE THREAD

**Issue by 0x90h** [ZXSpectrumVault/z80-spectrum-emulator#2]
have SRC-400.ZIP but without password :/

**Comment by bobsobol** [comment]
zip passwords aren't hard to crack, TBH.

I checked my registered disk, and it's also 2.01

**Comment by uav1606** [comment]
0x90h, can you share this archive?

**Comment by damieng** [comment]
I think we have 4.00 source incoming from another person - I'll check with Gerton and upload if he's okay with relicensing.
