### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bobsobol** [ZXSpectrumVault/z80-spectrum-emulator#3]
If Gurton has given permission, then as the new MIT license says, we should update the license included in the comments of source files, which states that you aren't allowed to modify and redistribute it.

MIT license:-
>"The above copyright notice and this permission notice shall be included in all
>copies or substantial portions of the Software."

Z80.8 :-
```
;   This file is part of the registered Spectrum emulator package 'Z80'
;   version 2.01, and may not be distributed."
```

These two are "inconsistent" and _will_ deter developers form contributing.

Personally, I'd quite like to try building an HX-DOS / Win32 binary. (ie. one that works on both Windows and DOS) and maybe see where we go from there. If we port the VGA stuff to SDL, and sort out the "`Sorry --- this computer is too fast!`" issue, it could be ported to Linux and BSD quite quickly from there, I think. ... I'm trying to get it running on a VIA C3 1Ghz embedded system, to load some tapes I can't find on the net, and add them to the global archive, so I need to resolve that "too fast" issue for myself anyway, but whatever I do, I'll be concerned about contributing back as this stands.

**Comment by damieng** [comment]
This isn't a repro for contributing, it's a vault of old source code for reference.

I wouldn't recommend using this as a base for new emulators, much more modern open source alternatives exist that don't rely on assembler like this one.
